### PR TITLE
Fixed #152 // PHP7 Reserved word "Object"

### LINKED ISSUE #152: PHP 7.2 - `Object` is a reserved word
In PHP 7.2.0RC2, `Object` is a reserved word. It'll trigger the error, "PHP Fatal error:  Cannot use 'Object' as class name as it is reserved ..."

* https://github.com/basho/riak-php-client/blob/develop/src/Riak/Object.php
* https://github.com/basho/riak-php-client/blob/develop/src/Riak/Command/Object.php

### PR DESCRIPTION
**Pull request by Geolim4**

### CODE REVIEW

**Comment by Geolim4** [comment]
The build has failed only because:
`The command "phpenv global 5.3" failed and exited with 1 during .` (Seems to be no longer supported by travis on this container)

Can we have a merge here please ? :)
Poke @alexmoore @debo @christophermancini @KevBurnsJr

Thanks

**Comment by Geolim4** [comment]
Since the maintainers does not give a damn to this repository I'm forking this one. Too bad there's so many inactive maintainers today :(

**Comment by alexmoore** [comment]
Like @cmancini said on the other PR, It’s not that we don’t care or don’t give a damn,  we simply do not have access to this repository anymore.  Basho is  essentially out of business, so our dev boxes, test boxes, etc. are all gone.  

https://www.theregister.co.uk/2017/07/31/end_of_the_road_for_basho_as_court_puts_biz_into_receivership/

**Comment by Geolim4** [comment]
I know it, but the thing is that they should made an announcement about this.
Even a "go to hell" would be appreciable :(

**Comment by debo** [comment]
I never had access to this repo, except from read only, and God knows how much time I spent trying to help those people out. Sad to say this @Geolim4 but, really give up; I don't want to get down to details but those people wasted at least 9 months of my life, so clearly not worthy the effort.

**Pull request closed without merging**
