### PR TITLE
Fixed #152 // PHP7 Reserved word "Object"

### LINKED ISSUE #152: PHP 7.2 - `Object` is a reserved word
In PHP 7.2.0RC2, `Object` is a reserved word. It'll trigger the error, "PHP Fatal error:  Cannot use 'Object' as class name as it is reserved ..."

* https://github.com/basho/riak-php-client/blob/develop/src/Riak/Object.php
* https://github.com/basho/riak-php-client/blob/develop/src/Riak/Command/Object.php

### PR DESCRIPTION
**Pull request by Geolim4**

### CODE REVIEW

**Comment by Geolim4** [comment]
Better to squash this Pull Request when merging... I'm getting crazy :(

**Comment by Geolim4** [comment]
Let's merge this thing please, gotta sleep now :(
Poke @alexmoore @debo @christophermancini @KevBurnsJr

**Comment by Geolim4** [comment]
Since the maintainers does not give a damn to this repository I'm forking this one. Too bad there's so many inactive maintainers today :(

**Comment by christophermancini** [comment]
@Geolim4 I would review and merge this if I could, sadly none of us have permissions on this project anymore since we are no longer with the organization.

**Pull request closed without merging**
